package com.tiltedgear.herocreator.util.factory

import scala.util.Random

object LoreGenerator {

  val rand = scala.util.Random

  val adjective : Seq[String] = Seq(
    "brave",
    "dumb",
    "smart",
    "professional",
    "adorable",
    "aggressive",
    "caring",
    "confident",
    "depressed",
    "confused",
    "envious",
    "slow",
    "eager",
    "grumpy",
    "odd",
    "handsome",
    "awful",
  )
  val strandwk : Seq[String] = Seq(
    "knife sharpening",
    "accurate bread slicing",
    "running fast",
    "potato peeling",
    "intense bowel movement",
    "buttering plates",
    "drinking water",
    "baking mud-pies",
    "sniffing animal feces",
    "turning wheels",
    "drinking acid",
    "tying shoelaces",
    "getting pregnant",
    "heights",
    "long conversations",
    "short people",
    "tall people",
    "old people",
    "young people",
    "short conversations",
    "small gaps",
    "wooden flooring",
    "cement",
    "bright lights",
    "teenagers",
    "fantasy creatures",
    "telling time",
    "staring",
    "cake",
    "bread",
    "wine",
    "not closing doors fully",
    "ice",
    "wearing a bag while sitting on a chair",
    "biting cutlery",
    "not finishing high fives",
    "not stirring coffee",
    "not folding paper properly",
    "tight pants",
    "social anxiety",
    "eating really fast",
    "mispronouncing names",
    "mispronouncing diagonal",
    "dropping rulers",
    "icing chihuahuas",
  )
  val seeking : Seq[String] = Seq(
    "An untreated torch.",
    "A rusty razor for shaving.",
    "A gold earring.",
    "A pair of silk gloves.",
    "A metal knife.",
    "A copper bracelet.",
    "A clove of garlic.",
    "A small lodestone.",
    "A pair of cloth gloves.",
    "A tusk from an unknown creature.",
    "A small hammer with a leather grip.",
    "A polished piece of quartz.",
    "A steel ring.",
    "A folded sheet of paper containing a list of places.",
    "A folded lace handkerchief containing a severed finger.",
    "A blue lace handkerchief smelling strongly of perfume.",
    "A rusty tinderbox engraved with a symbol.",
    "A set of stone dice.",
    "A scrunched up napkin containing a tooth.",
    "A set of fishing hooks.",
    "A green candle.",
    "A horn with pewter inlays.",
    "A folded sheet of paper containing a list of names.",
    "A wineskin half full of urine.",
    "A metal tankard.",
    "A glass bottle of expensive perfume.",
    "A silver toe ring.",
    "A pair of embroidered gloves.",
    "A small tinderbox engraved with a symbol.",
    "A brass signet ring.",
    "A few long matches.",
    "A dented tinderbox.",
    "An embroidered cloth scarf stained with something unidentifiable.",
    "A metal pipe.",
    "A pair of lace gloves.",
    "A wineskin filled with blood.",
    "A bracelet made of claws.",
    "A single silver coin with a head on both sides.",
    "A small cracked mirror.",
    "A broken flute.",
    "A lucky rabbit's foot amulet.",
    "A tiny wooden box filled with spices.",
    "A pair of foul-smelling stockings.",
    "An oiled whetstone.",
    "A few fishing hooks.",
    "A glass ring with a small red stone.",
    "A partially filled wineskin.",
    "A single copper coin, well worn with rubbing.",
    "A small hammer.",
    "A white candle.",
    "A few peacock feathers.",
    "A thick candle.",
    "A sealed letter containing terrible poetry."
  )

  def generateLore(name: String, faction : String, role : String, occupation : String) : String = {
    name + " A(n) " + Misc.GetRandomElement(adjective, rand) + " " + occupation + " from the lands of the " + faction + " seeking " + Misc.GetRandomElement(seeking, rand) + " " +
    name + "'s strengths are " + Misc.GetRandomElement(strandwk, rand) + " and " + Misc.GetRandomElement(strandwk, rand) + ". With strengths come weaknesses, these being " +
    Misc.GetRandomElement(strandwk, rand) + " and " + Misc.GetRandomElement(strandwk, rand) + "."
  }

}
